// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

type Trick struct {
	ID    int32   `db:"id" json:"id"`
	Name  *string `db:"name" json:"name"`
	Style *int32  `db:"style" json:"style"`
	Power *bool   `db:"power" json:"power"`
}
