// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Trick struct {
	ID    int32          `json:"id"`
	Name  sql.NullString `json:"name"`
	Style sql.NullInt32  `json:"style"`
	Power sql.NullBool   `json:"power"`
}
