// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Trick struct {
	ID    int32
	Name  sql.NullString
	Style sql.NullInt32
	Power sql.NullBool
}
